baseURL = "https://www.orgrim.net/"
languageCode = "fr"
title = "code. grind. sleep."
theme = ["hugo-notice", "anubis"]
paginate = 10
defaultContentLanguage = "fr"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Nicolas Thauvin"
  dateFormat = "2006-01-02"
  style = "dark"
  [params.customCSS]
    url1 = "css/custom.css"
    url2 = "css/syntax.css"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/orgrim"

  [[params.social]]
    name = "github"
    url = "https://github.com/orgrim"

[[menu.main]]
    name = "Blog"
    url = "post"
    weight = 1

[[menu.main]]
  name = "Categories"
  url = "categories"
  weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3


[[menu.footer]]
  name = "@orgrim"
  title = "Twitter"
  url = "https://twitter.com/orgrim"

[[menu.footer]]
  name = "github"
  url = "https://github.com/orgrim"

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    contentDir = "content/en"
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    contentDir = "content/fr"
